swagger: '2.0'
info:
  title: Mockster
  description: >-
    Say bye to Lorem ipsum! Used to generate random data for all kinds of
    purposes. Generated data is mimicking something that might be in the real
    world.
  version: '1.0'
host: apim-mockster-dev.azure-api.net
basePath: /v1
schemes:
  - https
consumes: []
produces: []
paths:
  /airlines:
    get:
      responses:
        '200':
          description: default
          schema:
            type: array
            items:
              type: object
              properties:
                aircraftType:
                  type: string
                  description: Returns a random aircraft type.
                  title: Aircraft Type
                airline: 
                  type: string
                  description: Returns a random airline.
                  title: Airline
                airplane:
                  type: string
                  description: Returns a random airplane.
                  title: Airplane
                airport:
                  type: string
                  description: Returns a random airport.
                  title: Airport
                departureAirport:
                  type: object
                  description: Returns a random departure airport.
                  title: Departure Airport
                  properties:
                    type:
                      type: string
                      description: Returns a random airport name.
                      title: Name
                    code:
                      type: string
                      description: Returns a random airport code.
                      title: IATA Code
                arrivalAirport:
                  type: object
                  description: Returns a random arrival airport.
                  title: Arrival Airport
                  properties:
                    type:
                      type: string
                      description: Returns a random airport name.
                      title: Name
                    code:
                      type: string
                      description: Returns a random airport code.
                      title: IATA Code
                flightNumber:
                  type: string
                  description: Returns a random flight number.
                  title: Flight Number
                recordLocator:
                  type: string
                  description: Returns a random record locator.
                  title: Record Locator
                seat:
                  type: string
                  description: Returns a random seat.
                  title: Seat
      summary: Get airlines mockdata
      description: Get rich airline mockup data. Returns an array of airline related properties, by default ten.
      operationId: getAirlines
      parameters:
        - name: count
          in: query
          required: false
          type: integer
          x-ms-summary: Count
          description: Define how many airlines you want returned. Default is ten.
  /animals:
    get:
      responses:
        '200':
          description: default
          schema:
            type: array
            items:
              type: object
              properties:
                bear:
                  type: string
                  description: Returns a random bear name.
                  title: Bear
                bird:
                  type: string
                  description: Returns a random bird name.
                  title: Bird
                cat:
                  type: string
                  description: Returns a random cat name.
                  title: Cat
                cetacean:
                  type: string
                  description: Returns a random cetacean name.
                  title: Cetacean
                cow:
                  type: string
                  description: Returns a random cow name.
                  title: Cow
                crocodilia:
                  type: string
                  description: Returns a random crocodilia name.
                  title: Crocodilia
                dog:
                  type: string
                  description: Returns a random dog name.
                  title: Dog
                fish:
                  type: string
                  description: Returns a random fish name.
                  title: Fish
                horse:
                  type: string
                  description: Returns a random horse name.
                  title: Horse
                insect: 
                  type: string
                  description: Returns a random insect name.
                  title: Insect
                lion:
                  type: string
                  description: Returns a random lion name.
                  title: Lion
                rabbit:
                  type: string
                  description: Returns a random rabbit name.
                  title: Rabbit 
                rodent:
                  type: string
                  description: Returns a random rodent name.
                  title: Rodent
                snake:
                  type: string
                  description: Returns a random snake name.
                  title: Snake
                type:
                  type: string
                  description: Returns a random animal type.
                  title: Type
      summary: Get animals mockdata
      description: Get rich data about animals. Returns an array of different animal ames, by default ten.
      operationId: getAnimals
      parameters:
        - name: count
          in: query
          required: false
          type: integer
          x-ms-summary: Count
          description: Define how many animals you want returned. Default is ten.
  /persons:
    get:
      responses:
        '200':
          description: default
          schema:
            type: array
            items:
              type: object
              properties:
                bio:
                  type: string
                  description: Returns a random short biography
                  title: Bio
                firstName:
                  type: string
                  description: Returns a random first name.
                  title: First Name
                lastName:
                  type: string
                  description: Returns a random last name.
                  title: Last Name
                fullName:
                  type: string
                  description: Generates a random full name.
                  title: Full Name
                jobArea:
                  type: string
                  description: Generates a random job area.
                  title: Job Area
                jobDescriptor:
                  type: string
                  description: Generates a random job descriptor.
                  title: Job Descriptor
                jobTitle:
                  type: string
                  description: Generates a random job title.
                  title: Job Title
                jobType:
                  type: string
                  description: Generates a random job type.
                  title: Job Type
      summary: Get people
      description: Get rich people mockup data. Returns an array of people with additional usefull properties, by default ten.
      operationId: getPeople
      parameters:
        - name: count
          in: query
          required: false
          type: integer
          x-ms-summary: Count
          description: Define how many people you want returned. Default is ten.
definitions: {}
parameters: {}
responses: {}
securityDefinitions: {}
security: []
tags: []
