name: Development deployment
on: 
  push: 
    branches:
      - development

permissions:
  id-token: write

jobs:
  setup: 
    name: Setup
    runs-on: windows-latest
    steps:

    # Checkout code from repo
    - name: Checkout code from development branch
      uses: actions/checkout@v4
      
    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    
    ## Build function
    - name: 'Resolve Project Dependencies Using Npm'
      shell: bash
      run: |
        pushd './function'
        npm install
        npm run build --if-present
        npm run test --if-present
        rm -r ./dist/**/*.map
        cp -r ./host.json ./package.json ./node_modules ./dist
        rm -r ./dist/node_modules/@types/
        rm -r ./dist/node_modules/azure-functions-core-tools/
        rm -r ./dist/node_modules/typescript/
        pushd './dist'
        mkdir dist
        mv ./src ./dist/
        zip -r ../deploy.zip ./*
        popd
        popd

    - name: print working directory
      run: |
        pwd
        ls

    # Upload build artifact
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: function
        path: ./function/deploy.zip
  infra:
    name: Deploy infrastructure to Azure
    runs-on: ubuntu-latest
    environment: development
    steps:
    
    # Checkout code from repo
    - name: Checkout code from development branch
      uses: actions/checkout@v4
    
    # Login to Azure
    - name: Authenticate to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
   
    # Deploy infrastructure
    - name: Run ARM deployment
      uses: azure/arm-deploy@v1
      with: 
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG_NAME }}
        template: ./arm/resources.json
        parameters: environment=DEV

  deployFunction:
    name: Deploy function to Azure
    runs-on: windows-latest
    environment: development
    needs: [setup, infra]
    steps:

       # Download build artifact
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: function

      # Login to Azure
      - name: Authenticate to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
   
      # Deploy function
      - name: Deploy function
        uses: azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ vars.FUNCTION_APP_NAME }}
          slot-name: production
          package: deploy.zip


   
