name: Development deployment
on: 
  push: 
    branches:
      - development

jobs:
  build: 
    runs-on: windows-latest
    steps:

    # Checkout code from repo
    - name: Checkout code from development branch
      uses: actions/checkout@v4
      
    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        
    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Install function core tools
    - name: Install Azure Function tools
      run: npm install azure-functions-core-tools@4
    
    # Instal Playwright browsers
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Start Azure Functions
    - name: Start Azure Functions
      run: nohup npm run start &

    # Seep before testing
    - name: Sleep for 30 seconds
      run: Start-Sleep -s 30

    # Run Playwright tests
    - name: Run Playwright tests
      run: npx playwright test

   
