name: Development deployment
on: 
  push: 
    branches:
      - development

jobs:
  setup: 
    name: Setup
    runs-on: ubuntu-latest
    steps:

    # Checkout code from repo
    - name: Checkout code from development branch
      uses: actions/checkout@v4
      
    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    
    ## Build function
    - name: 'Resolve Project Dependencies Using Npm'
      shell: bash
      run: |
        pushd './'
        npm install
        npm run build --if-present
        npm run test --if-present
        popd

    # Upload build artifact
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: functions
        path: ./dist
   

    
    

   
