name: Development deployment
on: 
  push: 
    branches:
      - development

jobs:
  build: 
    runs-on: windows-latest
    steps:

    # Checkout code from repo
    - name: Checkout code from development branch
      uses: actions/checkout@v4
      
    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        
    # Install dependencies
    - name: Install dependencies
      run: npm ci

    # Instal Playwright browsers
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Run Playwright tests
    - name: Run Playwright tests
      run: npx playwright test

   
